In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [254]:
torch.manual_seed(0)

target = torch.randint(0, 3, (1, 1)).squeeze(0)
preds = torch.randn(1, 3)

print("target:")
print(target)

print()
print("preds:")
print(preds)

loss_func = nn.CrossEntropyLoss()
loss = loss_func(preds, target)

print()
print("loss:", loss.item())

print()
print("my loss:---------------------------.")

# print()
# print("preds in one row:")
# preds = torch.sum(preds, dim = -1)
# print(preds)

# print()
# print("exp:")
# print(torch.exp(preds))

# print()
# print("exp sum:")
# print(torch.sum(torch.exp(preds)))

# print()
# print("log of exp sum:")
# print(torch.log(torch.sum(torch.exp(preds))))

print()
print("losses:")
print(-preds + torch.log(torch.sum(torch.exp(preds))))

target:
tensor([2])

preds:
tensor([[0.2072, 0.2699, 0.5507]])

loss: 0.9019474983215332

my loss:---------------------------.

losses:
tensor([[1.2455, 1.1828, 0.9019]])


In [253]:
torch.manual_seed(0)

target = torch.randint(0, 3, (1, 2)).squeeze(0)
preds = torch.randn(2, 3)

print("target:")
print(target)

print()
print("preds:")
print(preds)

loss = loss_func(preds, target)

print()
print("loss:", loss.item())

print()
print("losses:")
print(-preds + torch.log(torch.sum(torch.exp(preds))))

target:
tensor([2, 0])

preds:
tensor([[-0.2905, -1.0704,  1.2645],
        [-0.6874,  0.1604, -0.6065]])

loss: 0.8772002458572388

losses:
tensor([[2.2153, 2.9952, 0.6604],
        [2.6123, 1.7645, 2.5313]])


In [261]:
a=torch.Tensor([[4, 8, 3]])
y=torch.Tensor([2.]).long()

loss = loss_func(a, y)
print("loss:",loss.item())

print()
print(torch.exp(a))
print(torch.sum(torch.exp(a)))
print(torch.log(torch.sum(torch.exp(a))))
print(-a + torch.log(torch.sum(torch.exp(a))))

loss: 5.024744987487793

tensor([[  54.5981, 2980.9580,   20.0855]])
tensor(3055.6416)
tensor(8.0247)
tensor([[4.0247, 0.0247, 5.0247]])


In [339]:
torch.manual_seed(0)

loss = nn.CrossEntropyLoss()
a = torch.tensor(([0.88, 0.12], [0.51, 0.49]), dtype = torch.float)
print("pred:")
print(a)
target = torch.tensor([1, 0])
print("target:")
print(target)
print()

output = loss(torch.log(a), target)

print("output from loss with log input:", output)
print("above output with manual calculation:", (-torch.log(a[0, 1]) - torch.log(a[1, 0])) / 2)

print()
output = loss(a, target)
print("output from loss without log input:", output)

# print(torch.log(a))
# print((-a[0, 1] - a[1, 0]) / 2)
logsoftmax_func=nn.LogSoftmax(dim=1)
logsoftmax_output=logsoftmax_func(a)
print('logsoftmax_output:')
print(logsoftmax_output)

# print("above output with manual calculation:", (-torch.log(a[0, 1]) - torch.log(a[1, 0])) / 2)
# output = loss(F.log_softmax(a, dim =1), target)
# print("output from loss:", output)

# print((-torch.log(a[0, 1]) - torch.log(a[1, 0])) / 2)
# print()
# print(torch.log(a[0, 1]))
# print(torch.log(a[1, 0]))

# print(torch.log(a))

pred:
tensor([[0.8800, 0.1200],
        [0.5100, 0.4900]])
target:
tensor([1, 0])

output from loss with log input: tensor(1.3968)
above output with manual calculation: tensor(1.3968)

output from loss without log input: tensor(0.9134)
logsoftmax_output:
tensor([[-0.3837, -1.1437],
        [-0.6832, -0.7032]])


In [288]:
torch.manual_seed(0)

x_input=torch.randn(3,3)#Generate input randomly
print('x_input:\n',x_input)
y_target=torch.tensor([1,2,0])#Set the output specific value print('y_target\n',y_target)
 
 #Calculate the input softmax, at this time you can see that each row is added together and the result is 1
softmax_func=nn.Softmax(dim=1)
soft_output=softmax_func(x_input)
print('soft_output:\n',soft_output)
 
 #Take log on the basis of softmax
log_output=torch.log(soft_output)
print('log_output:\n',log_output)
 
 #Compare the combination of softmax and log with the output results of nn.LogSoftmaxloss (negative log-likelihood loss), and find that the two are consistent.
logsoftmax_func=nn.LogSoftmax(dim=1)
logsoftmax_output=logsoftmax_func(x_input)
print('logsoftmax_output:\n',logsoftmax_output)
 
#The default parameter configuration of NLLLoss in #pytorch is: reducetion=True, size_average=True
nllloss_func=nn.NLLLoss()
nlloss_output=nllloss_func(logsoftmax_output,y_target)
print('nlloss_output:\n',nlloss_output)
 
 #Use loss_func=nn.CrossEntropyLoss() in pytorch directly to see if it is the same as the calculation after NLLLoss
crossentropyloss=nn.CrossEntropyLoss()
crossentropyloss_output=crossentropyloss(x_input,y_target)
print('crossentropyloss_output:\n',crossentropyloss_output)

x_input:
 tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193]])
soft_output:
 tensor([[0.8446, 0.1349, 0.0205],
        [0.7511, 0.1438, 0.1051],
        [0.3484, 0.5382, 0.1134]])
log_output:
 tensor([[-0.1689, -2.0033, -3.8886],
        [-0.2862, -1.9392, -2.2532],
        [-1.0543, -0.6196, -2.1769]])
logsoftmax_output:
 tensor([[-0.1689, -2.0033, -3.8886],
        [-0.2862, -1.9392, -2.2532],
        [-1.0543, -0.6196, -2.1769]])
nlloss_output:
 tensor(1.7703)
crossentropyloss_output:
 tensor(1.7703)


In [388]:
cel_func = nn.CrossEntropyLoss()
x = torch.tensor(([0.88, 0.12], [0.51, 0.49]), dtype = torch.float)
print("x:")
print(x)
target = torch.tensor([1, 0])
print("target:")
print(target)
print()

x_log_softmax = F.log_softmax(x, dim = 1)
print("x_log_softmax:")
print(x_log_softmax)

nllloss_func = nn.NLLLoss()

loss1 = nllloss_func(x_log_softmax, target)

print()
print("nllloss with x_log_softmax and target:",loss1)
cel = cel_func(x, target)
print("cross entropy loss  with x and target:", cel)

print("----------------------------------------------------")
foo = torch.log(x)
# print(F.log_softmax(foo, 1))

print("log of x:")
print(foo)
print(nllloss_func(foo, target))
print(cel_func(foo, target))
# print()
# print("log of x:")
# print(torch.log(x))
# loss2 = nllloss_func(x, target)
# print()
# print("loss2:",loss2)
print((-torch.log(x[0, 1]) - torch.log(x[1, 0])) / 2)

# print(loss_func(x, target))
print("nllloss with x_log_softmax and target", nllloss_func(x, target))

x:
tensor([[0.8800, 0.1200],
        [0.5100, 0.4900]])
target:
tensor([1, 0])

x_log_softmax:
tensor([[-0.3837, -1.1437],
        [-0.6832, -0.7032]])

nllloss with x_log_softmax and target: tensor(0.9134)
cross entropy loss  with x and target: tensor(0.9134)
----------------------------------------------------
log of x:
tensor([[-0.1278, -2.1203],
        [-0.6733, -0.7133]])
tensor(1.3968)
tensor(1.3968)
tensor(1.3968)
nllloss with x_log_softmax and target tensor(-0.3150)


In [403]:
torch.manual_seed(0)

preds = torch.randn(2, 2)

print("preds:")
print(preds)

targets = torch.tensor([0, 1])#torch.randint(0, 3, (1, 2)).squeeze(0)
print()
print("targets:")
print(targets)

preds_log_softmax = F.log_softmax(preds, 1)
print()
print("preds_log_softmax:")
print(preds_log_softmax)

loss = cel_func(preds, targets)
print()
print("loss:", loss)

my_loss = -(preds_log_softmax[0, 0] + preds_log_softmax[1, 1]) / 2 
print("my loss:", my_loss)

preds:
tensor([[ 1.5410, -0.2934],
        [-2.1788,  0.5684]])

targets:
tensor([0, 1])

preds_log_softmax:
tensor([[-0.1482, -1.9826],
        [-2.8094, -0.0621]])

loss: tensor(0.1052)
my loss: tensor(0.1052)


## This is the actual code:

In [5]:
# torch.manual_seed(1)

preds = torch.randn(3, 5)
print("preds:")
print(preds)

targets = torch.randint(0, 5, (1, 3)).squeeze(0)
print()
print("targets:")
print(targets)

loss_func = nn.CrossEntropyLoss()
loss = loss_func(preds, targets)
print()
print("PyTorch loss:", loss)

preds_log_softmax = F.log_softmax(preds, 1)
print()
print("preds_log_softmax:")
print(preds_log_softmax)

my_loss = 0
for i in range(targets.shape[0]):
    my_loss += preds_log_softmax[i, targets[i].item()]
    
my_loss *= -1
my_loss /= targets.shape[-1] 
print()
print("my loss:", my_loss)

preds:
tensor([[ 0.5294, -0.9531,  1.4040,  0.2094, -0.1232],
        [ 0.3152,  0.0944,  0.2190,  0.5432,  0.6455],
        [ 0.0643, -0.4395, -0.4782,  0.6193,  1.8131]])

targets:
tensor([2, 4, 1])

PyTorch loss: tensor(1.6102)

preds_log_softmax:
tensor([[-1.5834, -3.0660, -0.7089, -1.9035, -2.2361],
        [-1.6785, -1.8993, -1.7747, -1.4505, -1.3482],
        [-2.2696, -2.7734, -2.8121, -1.7146, -0.5207]])

my loss: tensor(1.6102)
